name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  mod:
    name: Module Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node
        if: steps.mod-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Module Download
        if: steps.mod-cache.outputs.cache-hit != 'true'
        run: npm ci
  protobuf:
    name: Protobuf Generation
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Mod Cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Set Protobuf Cache
        uses: actions/cache@v3
        with:
          path: ./src/protobuf
          key: protobuf-${{ github.sha }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Generate code
        run: npm run gen
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        run: npm run lint
  type:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [mod, protobuf]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Set Protobuf Cache
        uses: actions/cache@v3
        with:
          path: ./src/protobuf
          key: protobuf-${{ github.sha }}
      - name: Type Check
        run: npm run type-check
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod, protobuf]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Set Protobuf Cache
        uses: actions/cache@v3
        with:
          path: ./src/protobuf
          key: protobuf-${{ github.sha }}
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Dockerfile
